# Generated by Django 6.0.6 on 2026-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade_central_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(),
        ),
    ]
