# Generated by Django 6.0.6 on 2026-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade_central_app', '0002_alter_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('RPG', 'RPG'), ('HORROR', 'Horror'), ('SPORTS', 'Sports'), ('FPS', 'FPS')], max_length=20),
        ),
    ]
